### ISSUE TITLE
How to change the password?

### ISSUE THREAD

**Issue by molakirlee** [jstrieb/link-lock#5]
Can we change the password?

**Comment by jstrieb** [comment]
Hi, thanks for checking out the project! 

It's not possible to change the password of a link that has already been made, but you can create unlimited locked links with different passwords for the same original URL. Hope that helps!

**Comment by jstrieb** [comment]
Please let me know if you have questions. If I don't see anything here for a few days, I will close the issue.

Thanks again for taking a look at the project!
